trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - "*"
# pool:
#   vmImage: "ubuntu-latest"
pool: 
 name: selfhosted

variables:
  - group: ABCDLite-action
  - name: serviceConnection
    value: vs-marketplace

stages:
  - stage: Release
    displayName: 'Build Extension'
    jobs:
      - job: BuildAndRelease
        displayName: 'Build and Release'
        steps:
          - task: UseNode@1
            displayName: 'Install Node.js'
            inputs:
              version: 22
          - task: TfxInstaller@4
            displayName: 'Install Tfx'
            inputs:
              version: "0.x"
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: 'install'
              workingDir: 'azure-pipelines'
          - task: Npm@1
            displayName: 'Build'
            inputs:
              command: 'custom'
              workingDir: 'azure-pipelines'
              customCommand: 'run build'
          - script: |
              TAG_NAME=$(Build.SourceBranchName)
              VERSION=${TAG_NAME#v}
              echo "##vso[task.setvariable variable=EXT_VERSION]$VERSION"
            displayName: 'Set version from tag'
          # - task: QueryAzureDevOpsExtensionVersion@4
          #   name: QueryVersion
          #   inputs:
          #     connectTo: 'VsTeam'
          #     connectedServiceName: '$(serviceConnection)'
          #     publisherId: '$(PublisherID)'
          #     extensionId: '$(ExtensionID)'
          #     versionAction: 'Patch'
          - task: PackageAzureDevOpsExtension@4
            displayName: 'Package Azure DevOps Extension'
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              extensionVersion: '$(EXT_VERSION)'
              updateTasksVersion: true
              updateTasksVersionType: 'patch'
              extensionVisibility: 'public'
              extensionPricing: 'free'
          - task: PublishAzureDevOpsExtension@4
            displayName: 'Publish Azure DevOps Extension'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '$(serviceConnection)'
              fileType: 'vsix'
              vsixFile: '$(PublisherID).$(ExtensionID)-$(EXT_VERSION).vsix'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              updateTasksVersion: false
              extensionVisibility: 'public'
              extensionPricing: 'free'
          - task: CopyFiles@2
            displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
            inputs:
              Contents: "**/*.vsix"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(ArtifactName)'
              publishLocation: 'Container'

